name: Deploy
on:
  release:
    types: [published]
jobs:
  deployment:
    if: startsWith(github.ref, 'refs/tags/nodes-dashboard-v')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Display raw tag
      run: echo "GITHUB_REF ${GITHUB_REF}"
