name: Deploy
on: [push]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Get raw tag
      run: echo ${GITHUB_REF}
    - name: Echo reference
      run: echo $(case "$GITHUB_REF" in "main") echo "main~1" ;; *) echo "origin/main" ;; esac)
    - name: diff
      id: diff
      run: >
        echo ::set-output
        name=chains_versions::$(
        git --no-pager diff
        $(case "$GITHUB_REF" in; "main") echo "main~1" ;; *) echo "origin/main" ;; esac)
        --name-only | paste -sd ' ')
    - name: echo diff
      env:
        CHAINS_VERSION: ${{ steps.diff.outputs.chains_versions }}
      run: echo $CHAINS_VERSION
