name: Deploy
on:
  release:
    types: [published]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:

    - name: Echo tag
      run: echo ${GITHUB_REF}

    - name: Echo tag 2
      run: echo ${GITHUB_REF#refs/tags/v*}
