name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Get raw tag
      id: vars
      run: echo ${GITHUB_REF}

    - name: Get tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      
    - name: Echo tag
      run: echo ${{ steps.vars.outputs.tag }}
