name: Deploy
on:
  release:
    types: [published]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Get tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v*}
    - name: Echo tag
      run: echo ${{ steps.vars.outputs.tag }}
